runtime: python39
entrypoint: gunicorn -b :$PORT --chdir invite/ invite.wsgi:application

handlers:
  # Any static request is routed to the static directory.
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto