version: '3.9'

services:
  invite: 
    build:
      context: ./invite
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      # Map src code into container
      - ./invite:/invite
      - ./static:/static
      - ./media:/media
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=0