version: '3.9'

services:
  invite: 
    build:
      context: ./invite
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./invite:/invite
    command: python3 manage.py runserver 0.0.0.0:8000