# Generated by Django 4.2.7 on 2023-11-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PencariRegu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.registereduser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UlasanProfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveIntegerField(default=0)),
                ("deskripsi_kerja_setim", models.TextField()),
                ("ulasan", models.TextField()),
                (
                    "diulas",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diulas",
                        to="user_profile.pencariregu",
                    ),
                ),
                (
                    "pengulas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pengulas",
                        to="user_profile.pencariregu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KetuaRegu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.pencariregu",
                    ),
                ),
            ],
        ),
    ]
