# Generated by Django 4.2.7 on 2023-11-28 16:34

import authentication.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TautanMediaSosial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website", models.CharField(blank=True, max_length=250)),
                ("instagram", models.CharField(blank=True, max_length=250)),
                ("twitter", models.CharField(blank=True, max_length=250)),
                ("linkedin", models.CharField(blank=True, max_length=250)),
                ("github", models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("middle_name", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "universitas",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("jurusan", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "keahlian",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=30, null=True
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "foto_profil",
                    models.ImageField(
                        upload_to=authentication.models.RegisteredUser.user_directory_path
                    ),
                ),
                (
                    "tautan_portfoilo",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "tautan_media_sosial",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.tautanmediasosial",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah_upvote", models.PositiveIntegerField(default=0)),
                ("jumlah_downvote", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.registereduser",
                    ),
                ),
            ],
        ),
    ]
