# Generated by Django 4.2.7 on 2023-12-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_members', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='bookmarked_lowongans',
            field=models.ManyToManyField(blank=True, to='find_members.lowonganregu'),
        ),
    ]
