# Generated by Django 4.2.7 on 2023-12-08 12:19

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereduser",
            name="foto_profil",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=authentication.models.RegisteredUser.user_directory_path,
            ),
        ),
    ]
