# Generated by Django 4.2.7 on 2023-12-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_registereduser_foto_profil'),
        ('authentication', '0002_registereduser_bookmarked_lowongans'),
    ]

    operations = [
    ]
